# /fluentd/dockerfile 
FROM fluentd:v1.9.1-debian-1.0

COPY /conf/* /fluentd/etc/

USER root

RUN gem uninstall -I elasticsearch && gem install elasticsearch -v 7.17.0
RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-document", "--version", "5.0.3"]
USER fluent