-- MySQL Script generated by MySQL Workbench
-- Sun May 30 21:06:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Lifresh
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Lifresh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Lifresh` DEFAULT CHARACTER SET utf8 ;
USE `Lifresh` ;

-- -----------------------------------------------------
-- Table `Lifresh`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lifresh`.`Account` ;

CREATE TABLE IF NOT EXISTS `Lifresh`.`Account` (
  `accountNo` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(24) NOT NULL,
  `password` VARCHAR(24) NOT NULL,
  `createDateTime` DATETIME NOT NULL,
  PRIMARY KEY (`accountNo`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lifresh`.`Plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lifresh`.`Plan` ;

CREATE TABLE IF NOT EXISTS `Lifresh`.`Plan` (
  `planNo` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL,
  `accountNo` INT NOT NULL,
  PRIMARY KEY (`planNo`),
  INDEX `accountNo_idx` (`accountNo` ASC),
  CONSTRAINT `accountNo`
    FOREIGN KEY (`accountNo`)
    REFERENCES `Lifresh`.`Account` (`accountNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lifresh`.`Classification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lifresh`.`Classification` ;

CREATE TABLE IF NOT EXISTS `Lifresh`.`Classification` (
  `cfNo` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(24) NOT NULL,
  `planNo` INT NULL,
  PRIMARY KEY (`cfNo`),
  INDEX `planNo_idx` (`planNo` ASC),
  UNIQUE INDEX `cf_unique` (`planNo` ASC, `name` ASC),
  CONSTRAINT `planNo`
    FOREIGN KEY (`planNo`)
    REFERENCES `Lifresh`.`Plan` (`planNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lifresh`.`MiddleClassification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lifresh`.`MiddleClassification` ;

CREATE TABLE IF NOT EXISTS `Lifresh`.`MiddleClassification` (
  `mcfNo` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(24) NOT NULL,
  `cfNo` INT NOT NULL,
  PRIMARY KEY (`mcfNo`),
  UNIQUE INDEX `mcf_unique` (`cfNo` ASC, `name` ASC),
  INDEX `cf_idx` (`cfNo` ASC),
  CONSTRAINT `cfNo`
    FOREIGN KEY (`cfNo`)
    REFERENCES `Lifresh`.`Classification` (`cfNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lifresh`.`DetailClassification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lifresh`.`DetailClassification` ;

CREATE TABLE IF NOT EXISTS `Lifresh`.`DetailClassification` (
  `dcfNo` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(24) NOT NULL,
  `mcfNo` INT NOT NULL,
  `dcfType` INT NOT NULL,
  PRIMARY KEY (`dcfNo`),
  INDEX `mcfNo_idx` (`mcfNo` ASC),
  UNIQUE INDEX `dcf_unique` (`mcfNo` ASC, `name` ASC),
  CONSTRAINT `mcfNo`
    FOREIGN KEY (`mcfNo`)
    REFERENCES `Lifresh`.`MiddleClassification` (`mcfNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lifresh`.`DoTask`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lifresh`.`DoTask` ;

CREATE TABLE IF NOT EXISTS `Lifresh`.`DoTask` (
  `doTaskNo` INT NOT NULL AUTO_INCREMENT,
  `dcfNo` INT NOT NULL,
  `startTime` DATETIME NOT NULL,
  `todayNo` INT NOT NULL,
  PRIMARY KEY (`doTaskNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lifresh`.`Today`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lifresh`.`Today` ;

CREATE TABLE IF NOT EXISTS `Lifresh`.`Today` (
  `todayNo` INT NOT NULL AUTO_INCREMENT,
  `planNo` INT NOT NULL,
  `todayDate` DATE NOT NULL,
  PRIMARY KEY (`todayNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lifresh`.`TimeTaskPlan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lifresh`.`TimeTaskPlan` ;

CREATE TABLE IF NOT EXISTS `Lifresh`.`TimeTaskPlan` (
  `timeTaskPlanNo` INT NOT NULL AUTO_INCREMENT,
  `dcfNo` INT NOT NULL,
  `startTime` DATETIME NOT NULL,
  `finishTime` DATETIME NOT NULL,
  `todayNo` INT NOT NULL,
  PRIMARY KEY (`timeTaskPlanNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lifresh`.`DoTaskPlan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lifresh`.`DoTaskPlan` ;

CREATE TABLE IF NOT EXISTS `Lifresh`.`DoTaskPlan` (
  `doTaskPlanNo` INT NOT NULL AUTO_INCREMENT,
  `dcfNo` INT NOT NULL,
  `startTime` DATETIME NOT NULL,
  `todayNo` INT NOT NULL,
  PRIMARY KEY (`doTaskPlanNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lifresh`.`TimeTask`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lifresh`.`TimeTask` ;

CREATE TABLE IF NOT EXISTS `Lifresh`.`TimeTask` (
  `timeTaskNo` INT NOT NULL AUTO_INCREMENT,
  `dcfNo` INT NOT NULL,
  `startTime` DATETIME NOT NULL,
  `finishTime` DATETIME NOT NULL,
  `todayNo` INT NOT NULL,
  PRIMARY KEY (`timeTaskNo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
