FROM golang:1.18
RUN go env -w GO111MODULE=auto
ENV GOPATH /app/go
ENV GOROOT /usr/local/go

#RUN go install
WORKDIR /app/go

# Copy everything from the current directory to the PWD (Present Working Directory) inside the container
COPY . /app/go


RUN apt-get update && apt-get upgrade -y


WORKDIR /app/go/src

RUN go mod tidy

# Install the package
#RUN go install -v github.com/go-sql-driver/mysql

EXPOSE 8000
RUN go build ./main.go
CMD ["go", "run", "./main.go"]